project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - icon: house
        text: "Changez Akram"
        href: https://changezakram.github.io/

      - text: Generative AI
        menu:
          - text: Gen AI Introduction
            href: index.qmd
          - text: Variational Autoencoders (VAEs)
            href: vae.qmd
          - text: Normalizing Flows
            href: flows.qmd
          - text: Energy-Based Models (EBMs)
            href: ebm.qmd
          - text: Diffusion Models
            href: diffusion.qmd


      - text: Large Language Models
        menu:
          - text: Transformers
            href: https://changezakram.github.io/Deep-Generative-Models/transformers.html
          - text: Post Training
            href: https://changezakram.github.io/Deep-Generative-Models/post-training.html
          - text: NLP Evaluation
            href: https://changezakram.github.io/Deep-Generative-Models/nlp-eval.html

      - text: Agentic AI
        menu:
          - text: Introduction
            href: https://changezakram.github.io/agentic-ai/agentic-ai.html
          - text: Agentic Analytics
            href: https://changezakram.github.io/agentic-ai/agentic-analytics.html
          - text: Small Language Models
            href: https://changezakram.github.io/Deep-Generative-Models/slm.html
          - text: Building Safe & Secure Agentic AI
            href: https://changezakram.github.io/agentic-ai/agentic_ai_safety.html

      - text: AI Strategy
        menu:
          - text: Building the AI-First Bank
            href: https://changezakram.github.io/Deep-Generative-Models/gen-ai-use-cases/ai_first_bank.html
          - text: Gen AI in Banking
            href: https://changezakram.github.io/Deep-Generative-Models/gen-ai-use-cases/banking-use-cases.html
          - text: Gen AI in Healthcare
            href: https://changezakram.github.io/Deep-Generative-Models/gen-ai-use-cases/healthcare-use-cases.html

      - text: Math Review
        menu:
          - text: Linear Algebra
            href: https://changezakram.github.io/math-review/linear-algebra.html
          - text: Calculus
            href: https://changezakram.github.io/math-review/calculus.html
          - text: Probability
            href: https://changezakram.github.io/math-review/probability.html

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: true
    html-math-method: mathjax

resources:
  - images/**